### ISSUE TITLE
Bug: LibreWolf browser is being mistaken for Firefox

### ISSUE THREAD

**Issue by Bamboy** [Circadiaware/webactogram#10]
LibreWolf is a fork of Firefox but with more focus on privacy/security. I've only been using it as my main browser for a few months. (previously used chrome)
Wanted to try this little tool out but I think it was mistaking LibreWolf for firefox, which was not installed on my Windows 10 system at all. It was refusing to run at all because it was trying to import firefox history, which didn't exist. The only way I could get the tool to run was to manually comment out the firefox importing code.

Figured I would mention it here considering it completely breaks the tool.

**Comment by lrq3000** [comment]
Thank you for reporting this bug, I'll investigate how to properly fix it.

**Comment by lrq3000** [comment]
Should be fixed in v0.4.0, thank you for reporting this issue! Please let me know if this issue still pops up in the future (but it shouldn't, we are now using an external module that specifically supports LibreWolf!).
